version: "3"
services:
  mysql:
    image: mysql:5.7
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: magento1
      MYSQL_DATABASE: magento1
      MYSQL_USER: magento1
      MYSQL_PASSWORD: magento1
    volumes:
      - "./db:/var/lib/mysql"
networks:
  webnet:
