version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    build:
      context: docker-images/nginx/
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
    volumes:
      - "php:/var/www/html"
  magento:
    deploy:
      restart_policy:
        condition: on-failure
    build:
      context: docker-images/php/
    volumes:
      - "php:/var/www/html"
networks:
  webnet:
volumes:
  php:
