version: "3"
services:
  magento:
    deploy:
      restart_policy:
        condition: on-failure
    labels:
      magento.container: "Magento"
    image: magento-php:latest
    ports:
      - "3306:3306"
    networks:
      - webnet
    volumes:
      - "php:/var/www/magento2"
  web:
    # replace username/repo:tag with your name and image details
    image: andrediogo92/nginx-mage:latest
    deploy:
      restart_policy:
        condition: on-failure
    labels:
      web.container: "Nginx"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
    volumes:
      - "php:/var/www/html/magento2"
      - "./docker-images/nginx/vhosts.conf:/etc/nginx/conf.d/default.conf"
networks:
  webnet:
volumes:
  php:
