version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: andrediogo92/nginx-mage:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
    volumes:
      - "php:/var/www/html/web"
      - "./docker-images/nginx/vhosts.conf:/etc/nginx/conf.d/default.conf"
  magento:
    deploy:
      restart_policy:
        condition: on-failure
    image: andrediogo92/magento-php:latest
    networks:
      - webnet
    volumes:
      - "php:/var/www/html/web"
networks:
  webnet:
volumes:
  php:
