# Use an official Ubuntu image as a parent image
FROM php:7.1


# Install any needed packages
RUN buildDeps=" \
        libpng12-dev \
        libjpeg-dev \
        libmcrypt-dev \
        libxml2-dev \
        freetype* \
    "; \
    set -x \
    && apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-configure \
    gd --with-png-dir=/usr --with-jpeg-dir=/usr --with-freetype-dir \
    && docker-php-ext-install \
    gd \
    mbstring \
    opcache \
    mcrypt \
    curl \
    iconv \
    xml \
    intl \
    json \
    odbc \
    xsl \
    mysql \
    pdo_mysql \
    mysqli \
    bcmath \
    soap \
    zip \
    && apt-get auto-remove -y

COPY php.ini /usr/local/etc/php/php.ini
COPY php-fpm.conf /usr/local/etc/

# Make sure the volume mount point is empty
RUN rm -rf /var/www/html/*

# Install magerun
RUN curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer && \
    composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition /var/www/html/web && \
    cd /var/www/html/web && \
    find var generated vendor pub/static pub/media app/etc -type f -exec chmod u+w {} \; && \
    find var vendor generated pub/static pub/media app/etc -type d -exec chmod u+w {} \; && \
    chmod u+x bin/magento && \
    apt-get update && \
    apt-get install -qy mysql-client && \
    export PATH=$PATH:/var/www/html/web/bin && \
    magento setup:install --admin-firstname=SDB --admin-lastname=SDB --admin-email=sdbuminho@gmail.com --admin-user={{magento_user}} --admin-password={{magento_password}} --db-host={{db_host}} --db-user={{db_user}} --db-password={{db_password}} --use-rewrites=1
